version: "3"

networks:
  tk-pro-net:
    driver: bridge

services:
  noco-app:
    image: registry.cn-shanghai.aliyuncs.com/leon-pu/noco:amd64-latest
    container_name: tk_noco_app_c
    networks:
      - tk-pro-net
    environment:
      - APP_KEY=taixiangtk
      - DB_DIALECT=postgres
      - DB_HOST=106.55.173.188
      - DB_PORT=9201
      - DB_DATABASE=tiktok
      - DB_USER=postgres
      - DB_PASSWORD=Leon.pu199139!
      - DB_TIMEZONE=+08:00
      - INIT_APP_LANG=zh-CN
      - DB_LOGGING=off
      - LOGGER_LEVEL=error
    volumes:
      - /var/tk/storage:/app/nocobase/storage
    ports:
      - "9900:80"
    init: true
    restart: always
